apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: v1.9.1
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    installCRDs: true
    extraArgs:
    - --enable-certificate-owner-ref=true
