{
 "title": "Active Alerts",
 "description": "Dashboard to visualize only Open(LIVE) Alerts of AlertManager",
 "tags": [
  "alertmanager",
  "open-alerts"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "alertmanager",
    "label": "Alertmanager",
    "query": "camptocamp-prometheus-alertmanager-datasource"
   },
   { "name": "cluster", "label": "Cluster", "query": "label_values(cluster)" },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(cluster=~\"$cluster\")"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(cluster=~\"$cluster\", environment=~\"$environment\")"
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": "label_values(cluster=~\"$cluster\", environment=~\"$environment\", namespace=~\"$namespace\")"
   },
   {
    "name": "alertname",
    "label": "Alert",
    "query": "label_values(cluster=~\"$cluster\", environment=~\"$environment\", namespace=~\"$namespace\", severity=~\"$severity\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster=~\"$cluster\", environment=~\"$environment\",  namespace=~\"$namespace\", severity=~\"$severity\",alertname=~\".*\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Total Critical",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster=~\"$cluster\", environment=~\"$environment\",  namespace=~\"$namespace\", severity=~\"critical\",alertname=~\".*\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Total Warning",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster=~\"$cluster\", environment=~\"$environment\",  namespace=~\"$namespace\", severity=~\"warning\",alertname=~\".*\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Target Down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster=~\"$cluster\", environment=~\"$environment\",  namespace=~\"$namespace\", alertname=~\"TargetDown\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "GitOps Manifests Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster=~\"$cluster\", environment=~\"$environment\",  namespace=~\"$namespace\", alertname=~\"FluxManifestErrors\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Helm Release Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster=~\"$cluster\", environment=~\"$environment\",  namespace=~\"$namespace\", alertname=~\"HelmReleaseError\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Istio Gateway Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster=~\"$cluster\", environment=~\"$environment\",  alertname=~\"IstioGatewayAvailabilityDrop\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Istiod Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster=~\"$cluster\", environment=~\"$environment\",  alertname=~\"IstiodAvailabilityDrop\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "OPEN ALERTS",
   "type": "table-old",
   "description": "MAKE SURE TO SCROLL TO BOTTOM AND CHECK FOR MORE ALERTS",
   "gridPos": { "h": 98, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "cluster=~\"$cluster\", environment=~\"$environment\", namespace=~\"$namespace\",  severity=~\"$severity\",alertname=~\"$alertname\"",
     "labelSelector": "*",
     "legendFormat": "{{ msg }}",
     "target": "Query",
     "type": "table"
    }
   ]
  }
 ]
}