{
 "title": "Helm Operator Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "DS_LOKI", "query": "loki" },
   { "name": "logs_search" }
  ]
 },
 "panels": [
  { "title": "Main Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Helm Releases Synced",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "flux_helm_operator_release_count{}",
     "legendFormat": "Synced Manifests"
    }
   ]
  },
  {
   "title": "Helm Release Sync Duration",
   "type": "graph",
   "gridPos": { "h": 12, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(flux_helm_operator_release_action_duration_seconds_sum{action=\"sync\"}[5m]) > 0",
     "legendFormat": "{{release_name}} sync"
    }
   ]
  },
  {
   "title": "Helm Releases Not Synced",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "flux_helm_operator_release_queue_length_count{}"
    }
   ]
  },
  { "title": "Releases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Helm Releases - Released",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "flux_helm_operator_release_condition_info{condition=\"Released\"} == 1"
    }
   ]
  },
  {
   "title": "Helm Releases - Failed",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "flux_helm_operator_release_condition_info{condition=\"Released\"} == -1"
    }
   ]
  },
  {
   "title": "Helm Releases - RolledBack",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "flux_helm_operator_release_condition_info{condition=\"RolledBack\"} == 1"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Helm Operator Logs",
   "type": "logs",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{app=\"helm-operator\"} |~ \"$logs_search\""
    }
   ]
  }
 ]
}