{
 "title": "Grafana Loki Dashboard for Istio Service Mesh",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   { "name": "label_name", "label": "Label name", "query": "label_names()" },
   { "name": "label_value", "label": "Label Value", "query": "label_values($label_name)" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({$label_name=~\"$label_value\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({$label_name=~\"$label_value\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "KPI's", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"}[$__interval]))  "
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (response_code) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} \n| json\n| __error__=\"\"\n| response_code=~\"0|2..|3..|4..|5..\"  [$__interval])) ",
     "legendFormat": "Status code: {{response_code}}"
    }
   ]
  },
  {
   "title": "Istio logs in bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "bytes_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "$label_value"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (upstream_cluster) (sum_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"}\n| json\n| unwrap bytes_sent\n|  __error__=\"\"\n[$__interval]))"
    }
   ]
  },
  {
   "title": "Recent requests",
   "type": "logs",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"}\n| json\n| line_format \"{{ .method }} request to {{ .path }} with HTTP status: {{.response_code}} upstream cluster {{ .upstream_cluster}} \""
    }
   ]
  },
  {
   "title": "Realtime visitors ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count (sum by (x_forwarded_for) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"}\n| json\n| path != \"/\" and user_agent != \"Edge Health Probe\" |user_agent !=\"\"\n[$__interval])))"
    }
   ]
  },
  {
   "title": "# Istio log lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"}[$__interval])"
    }
   ]
  },
  {
   "title": "% of 5xx requests ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json\n| response_code>=500 |__error__=\"\" [$__interval]))\n/\n(sum(count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json\n| __error__=\"\" [$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "% of requests by Googlebot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |~ \"Googlebot|Slack.+\")[$__interval])) / (sum(count_over_time(({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} !~ \"Googlebot|Slack.+\")[$__interval])) / 100)"
    }
   ]
  },
  { "title": "Request statistics over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "95th percentile of duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"}\n| json\n| unwrap duration \n| path != \"/\"|user_agent !=\"\"\n|  __error__=\"\"  [$__interval]) by (host)",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "max by (host) (max_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"}\n| json\n| unwrap duration \n| path != \"/\" |user_agent !=\"\"\n|  __error__=\"\"  [$__interval]))",
     "legendFormat": "max latency"
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (response_code ) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} \n| json | __error__=\"\"\n | response_code =~\"0|2..|3..|4..|5..\" \n[$__interval])) ",
     "legendFormat": "Status code: {{response_code}}"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json\n| response_code=200 \n| unwrap bytes_sent\n|  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  { "title": "Acquisition and Behaviour", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Top 10 paths by duration in last 1h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, max_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"}\n| json\n| unwrap duration\n|  response_code = 200 and path != \"/\" and user_agent != \"Edge Health Probe\" |user_agent !=\"\"\n| __error__=\"\" [$__interval]) by (path))",
     "legendFormat": "{{path}} "
    }
   ]
  },
  {
   "title": "Top 10 visitor IPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "topk(100, sum by (x_forwarded_for) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | x_forwarded_for !=\"\" | x_forwarded_for !~ \"10.123.+\"|  __error__=\"\" [$__interval])))",
     "legendFormat": "{{x_forwarded_for}}"
    }
   ]
  },
  {
   "title": "Top 10 paths by duration in last 1h",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10, max_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"}\n| json\n| unwrap duration\n|  response_code = 200 and path != \"/\" and user_agent != \"Edge Health Probe\" |user_agent !=\"\"\n| __error__=\"\" [$__interval]) by (path))",
     "legendFormat": "{{path}} "
    }
   ]
  },
  {
   "title": "Top 10 Requested Pages",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "topk(10, sum by (path) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} \n!~ `.ico|.svg|.css|.png|.txt|.js|.xml`\n| json\n| response_code= 200 and path != \"/\"  and user_agent != \"Edge Health Probe\" |user_agent !=\"\"\n| __error__=\"\" [$__interval])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Top 10 User Agents",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "topk(10, sum by (user_agent) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | user_agent != \"Edge Health Probe\" |user_agent !=\"\"\n| __error__=\"\" [$__interval])))",
     "legendFormat": "{{user_agent}}"
    }
   ]
  }
 ]
}