apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
spec:
  releaseName: promtail
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "3.10.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    config:
      lokiAddress: http://loki-loki-distributed-gateway.monitoring/loki/api/v1/push
